[2025-05-12T07:04:31.307+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_brewery.extract_breweries manual__2025-05-12T07:04:30.792626+00:00 [queued]>
[2025-05-12T07:04:31.311+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_brewery.extract_breweries manual__2025-05-12T07:04:30.792626+00:00 [queued]>
[2025-05-12T07:04:31.311+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-12T07:04:31.316+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): extract_breweries> on 2025-05-12 07:04:30.792626+00:00
[2025-05-12T07:04:31.318+0000] {standard_task_runner.py:57} INFO - Started process 52 to run task
[2025-05-12T07:04:31.323+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_brewery', 'extract_breweries', 'manual__2025-05-12T07:04:30.792626+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/brewery_pipeline.py', '--cfg-path', '/tmp/tmpyrux_bze']
[2025-05-12T07:04:31.324+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask extract_breweries
[2025-05-12T07:04:31.347+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_brewery.extract_breweries manual__2025-05-12T07:04:30.792626+00:00 [running]> on host 291ade9df45c
[2025-05-12T07:04:31.377+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_brewery' AIRFLOW_CTX_TASK_ID='extract_breweries' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T07:04:30.792626+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-12T07:04:30.792626+00:00'
[2025-05-12T07:04:31.378+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-12T07:04:31.379+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/scripts/extract_breweries']
[2025-05-12T07:04:31.384+0000] {subprocess.py:86} INFO - Output:
[2025-05-12T07:04:31.393+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/***/scripts/extract_breweries': [Errno 2] No such file or directory
[2025-05-12T07:04:31.394+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-12T07:04:31.400+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-12T07:04:31.403+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_brewery, task_id=extract_breweries, execution_date=20250512T070430, start_date=20250512T070431, end_date=20250512T070431
[2025-05-12T07:04:31.409+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task extract_breweries (Bash command failed. The command returned a non-zero exit code 2.; 52)
[2025-05-12T07:04:31.421+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-12T07:04:31.430+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
