[2025-05-12T07:00:37.425+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_brewery.extract_breweries manual__2025-05-12T07:00:36.723399+00:00 [queued]>
[2025-05-12T07:00:37.432+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_brewery.extract_breweries manual__2025-05-12T07:00:36.723399+00:00 [queued]>
[2025-05-12T07:00:37.432+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-12T07:00:37.437+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): extract_breweries> on 2025-05-12 07:00:36.723399+00:00
[2025-05-12T07:00:37.439+0000] {standard_task_runner.py:57} INFO - Started process 43 to run task
[2025-05-12T07:00:37.442+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_brewery', 'extract_breweries', 'manual__2025-05-12T07:00:36.723399+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/brewery_pipeline.py', '--cfg-path', '/tmp/tmpxegu8nfn']
[2025-05-12T07:00:37.443+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask extract_breweries
[2025-05-12T07:00:37.476+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_brewery.extract_breweries manual__2025-05-12T07:00:36.723399+00:00 [running]> on host 291ade9df45c
[2025-05-12T07:00:37.511+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_brewery' AIRFLOW_CTX_TASK_ID='extract_breweries' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T07:00:36.723399+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-12T07:00:36.723399+00:00'
[2025-05-12T07:00:37.512+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-12T07:00:37.513+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/scripts/extract_breweries']
[2025-05-12T07:00:37.520+0000] {subprocess.py:86} INFO - Output:
[2025-05-12T07:00:37.539+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/***/scripts/extract_breweries': [Errno 2] No such file or directory
[2025-05-12T07:00:37.541+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-12T07:00:37.546+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-12T07:00:37.549+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_brewery, task_id=extract_breweries, execution_date=20250512T070036, start_date=20250512T070037, end_date=20250512T070037
[2025-05-12T07:00:37.555+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task extract_breweries (Bash command failed. The command returned a non-zero exit code 2.; 43)
[2025-05-12T07:00:37.586+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-12T07:00:37.597+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
